### PR TITLE
Update logging entries

### PR DESCRIPTION
**Pull request by aradiquez**
some fixes in the Analytics according to this standards document: 
https://docs.google.com/spreadsheets/d/1xf0Bj5tjlkq-BWoOIUf7tU8oNvFzsHM3iOrfmGmqpbA/edit#gid=0

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/textchat-acc-pack/pull/206" target="_blank">ReviewNinja

**Comment by Lucashuang0802** [comment]
👍  please update the branch.

**Comment by marinaserranomontes** [comment]
retest please

**Comment by marinaserranomontes** [comment]
@aradiquez  it seems to be out of date, please, could you review it? I think you need to update your branch with the last develop changes to fix the conflicts. Thanks!!

**Pull request merged**
