### PR TITLE
OTS-320

### PR DESCRIPTION
**Pull request by andreaphillips**
## Pull request checklist

- [ ] All tests pass. Demo project builds and runs.👍
- [x] I have resolved any merge conflicts. Confirmation: 👍

## What's in this pull request?
- adding active class to the send message button when we type.

Please delete branch after merge

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/textchat-acc-pack/pull/214" target="_blank">ReviewNinja

**Comment by marinaserranomontes** [comment]
@adrice727 can we close/merge this PR please?

**Comment by marinaserranomontes** [comment]
@ggoldens @adrice727 can we merge/close this PR, please? Thanks!

**Comment by ggoldens** [comment]
Closing this PR since this solution was included in the PR #222

**Pull request closed without merging**
