### PR TITLE
OTS-420: text chat refactor

### PR DESCRIPTION
**Pull request by jneimantokbox**
## Pull request checklist

- [ ] All tests pass. Demo project builds and runs.
- [ ] I have resolved any merge conflicts. Confirmation: ____

## What's in this pull request?

>...

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/opentok/textchat-acc-pack/pull/217" target="_blank">ReviewNinja

**Comment by jneimantokbox** [comment]
@marinaserranomontes , @Lucashuang0802 , @adrice727 : please review and merge if approved

**Comment by Lucashuang0802** [comment]
👍

**Comment by marinaserranomontes** [comment]
LGTM

**Pull request merged**
